name: Test Action

on:
  push:
    branches:
      - main  # or another branch you want to trigger the action

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Hello World script
        run: echo "Hello, world!"
