name: Test GitHub Action

on:
  push:
    branches:
      - main  # Change to the relevant branch
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 22f2001649@ds.study.iitm.ac.in
        run: echo "Hello, world!"
